# https://docs.codecov.com/docs/common-recipe-list
coverage:
  status:
    project:
      default:
        threshold: 1%  # the leniency in hitting the target
        informational: true
    patch:
      default:
        informational: true

ignore:
  - "**/test/"
  - "**/3rdparty/"
  - "**/demo/"
  - "**/example/"
  - "**/apps/"
  - "**/samples/"
  - "**/tutorial/"
  - "**/modules/gui"
  - "**/modules/io/src/parallel-port"
  - "**/modules/robot"
  - "**/modules/sensor"
