name: MacOS-Linux-conda-CI

on: [push,pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  visp-conda:
    name: ${{ matrix.os }} - Python ${{ matrix.python-version }} ${{ matrix.build_type }} ${{ matrix.cxx_options }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        build_type: [Release]
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: conda-incubator/setup-miniconda@v3
      if: startsWith(matrix.os,'ubuntu') == true
      with:
        activate-environment: visp
        auto-update-conda: true
        environment-file: .github/workflows/conda/environment_linux.yml
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false

    - uses: conda-incubator/setup-miniconda@v3
      if: startsWith(matrix.os,'macos') == true
      with:
        activate-environment: visp
        auto-update-conda: true
        environment-file: .github/workflows/conda/environment_macos.yml
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false

    - name: Show conda config
      shell: bash -el {0}
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
        printenv | sort

    - name: Build visp python bindings
      shell: bash -el {0}
      run: |
        mkdir build
        cd build

        cmake .. \
          -G "Ninja" \
          -DCMAKE_PREFIX_PATH=$CONDA_PREFIX \
          -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

        # Build
        cmake --build . --target visp_python_bindings

        # Test Python import
        cd modules/python/bindings
        python -c "import visp"

  check:
    if: always()
    name: check-macos-linux-conda

    needs:
    - visp-conda

    runs-on: Ubuntu-latest

    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
